prison/accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
	re_path(r'^signup/$', views.signup, name="signup"),
	re_path(r'^login/$', views.login_view, name="login"),
	
]

prison/affer/urls.py
from django.urls import path, include, re_path

from django.urls import path
from .views import *
from .import views

app_name = "affer"


urlpatterns = [
    path('taga/',  views.tags_list, name="tags_list_url"),
    path('taga/<str:slug>/', views.tags_detail, name="tags_detail_url"),
    path('tags/', views.tags_list, name="tags_list_url"),
    path('tag/create', TagCreate.as_view(), name="tag_create_url"),
    path('affe/', views.affers_page, name="affers_page"),



]

prison/akimov/urls.py
from django.urls import path, re_path
from . import views

app_name = 'akimov'

urlpatterns = [
	path('', views.home, name='home'),
	re_path(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
	


]

prison/prison/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('akimov.urls')),
    re_path('', include('accounts.urls')),
    path('', include('affer.urls'))
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prison/accounts/models.py
from django.db import models

# Create your models here.

prison/affer/models.py
from django.db import models

# Create your models here.from django.db import models

# Create your models here.
class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    thumb = models.ImageField(default='default.png', blank=True, upload_to='media')

    def __str__(self):
        return self.title

prison/akimov/models.py
from django.db import models


class New(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	thumb = models.ImageField(default='default.png', blank=True)

def __str__(self):
	return self.name

prison/affer/forms.py
from django import forms
from .models import Tag
from django.core.exceptions import ValidationError


class TagForm(forms.Form):
    title  = forms.CharField(max_length=50)
    slug = forms.CharField(max_length=50)
    thumb = forms.ImageField()


    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()

        if new_slug == 'create':
            raise ValidationError('Slug may not be "Create"')
        if Tag.objects.filter(slug__iexact=new_slug).count():
            raise ValidationError('Slug must be unique. We have "{}" slug already'.format(new_slug))
        return new_slug

    def save(self):
        new_tag = Tag.objects.create(
            title=self.cleaned_data['title'],
            slug=self.cleaned_data['slug'],
            thumb=self.cleaned_data['thumb']

        )
        return new_tag

prison/accounts/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login

def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request,user)
			return redirect('akimov:home')
	else:
		form = UserCreationForm()
	return render(request, 'accounts/signup.html', {'form':form})




def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('akimov:home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

prison/affer/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.views.generic import View
from .models import  Tag
from .forms import TagForm

def affers_page(request):
    tags = Tag.objects.all()
    return render(request, 'affer/affers_page.html', {'tags':tags})

def tags_list(request):
    tags = Tag.objects.all()
    return render(request, 'affer/tags_list.html', context={'tags':tags})



def tags_detail(request, slug):
    tag = Tag.objects.get(slug__iexact=slug)
    return render(request, 'affer/tags_detail.html', context={'tag':tag})


#class TagDetail( View):
    #def get(self, request, slug):
        #tag = Tag.objects.get(slug__iexact=slug2)
        #tag = get_object_or_404(Tag, slug__iexact=slug)
        #return render(request, 'affer/tags_detail.html', context={'tag':tag})




class TagCreate(View):
    def get(self, request):
        form = TagForm()
        return render(request, 'affer/tags_create.html', context={'form':form})

    def post(self, request):
        bound_form = TagForm(request.POST, request.FILES)

        if bound_form.is_valid():
            new_tag = bound_form.save()
            return redirect('akimov:home')
        return render(request, 'affer/tags_create.html', context={'form':bound_form})

prison/akimov/views.py
from django.shortcuts import render
from .models import New 
from affer.models import Tag 



def home(request):
	
	news = New.objects.all()
	return render(request, 'akimov/home.html', {'news':news},)

def detail(request, slug):
	new = New.objects.get(slug=slug)
	return render(request, 'akimov/detail.html', {'new':new})

prison/accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="/static/stylelog.css">
  </head>
  <body>
    <div class="pic">

    </div>
    <div class="content">
    	<h1 class="log">LOgin</h1>

      <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
          <input type="submit" value="Login">

      </form>
    </div>
  </body>
</html>

prison/accounts/templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

  </head>
  <body>
    <div class="content">

      <form class="site-form" action="" method="post">
        <h1 class="log">Signup</h1>
        {% csrf_token %}

        {{ form }}
        <input type="submit" value="Signup" >
      </form>
    </div>
  </body>
</html>

prison/affer/templates/affer/affers_page.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
		<link rel="stylesheet" type="text/css" href="/static/det-style.css">

</head>
<body>

	<div class="bg">
    <div class="content">
             
		{% for tag in tags %}
			<h2>{{ tag.title }}</h2>
			<img src="{{ tag.thumb.url }}">
		{% endfor %}
    </div>
  </div>

	
</body>
</html>

prison/affer/templates/affer/tags_create.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <form class="" enctype="multipart/form-data" action="{% url 'affer:tag_create_url' %}" method="post">
        {% csrf_token %}
          {{ form.title }}
          {{ form.slug }}
          {{ form.thumb }}

        <button type="submit" class="btn btn-primary">Create Tag</button>
      </form>
    </div>
  </body>
</html>

prison/affer/templates/affer/tags_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
        <h1 class="mt-5">Post with  "{{ tag.title|title }}" tag:</h1>
        <img src="{{ tag.thumb.url }}" />

    </div>
  </body>
</html>

prison/affer/templates/affer/tags_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <h1 class="mb-5">Tags:</h1>
      {% for tag in tags %}
        <h3><a href="{% url 'affer:tags_detail_url' slug=tag.slug %}" >{{ tag.title }}</a></h3>
      {% endfor %}
    </div>
  </body>
</html>

prison/akimov/templates/akimov/detail.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
		<link rel="stylesheet" type="text/css" href="/static/det-style.css">

</head>
<body>
	<div class="bg">
    <div class="content">
             
		<h2>{{ new.title }}</h2>
		<img src="{{ new.thumb.url }}">
    </div>
  </div>
  
</body>
</html>

prison/akimov/templates/akimov/home.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Homepage</title>
	<link rel="stylesheet" type="text/css" href="/static/style.css">
</head>
<body>
	<div class="head">
		<h2>My server</h2>
	</div>
		{% for new in news %}
			<h2 class= "det"><a href="{% url 'akimov:detail' slug=new.slug %}">{{ new.title }}</a></h2>

			
		{% endfor %}

		
		<div class="users"> 
				<a href="{% url 'accounts:signup' %}">Signup</a>
				<a href="{% url 'accounts:login' %}">Login</a>
		</div>
		

	<div>
		<a href="{% url 'affer:tag_create_url' %}">Create Article</a>
		<a href="{% url 'affer:affers_page' %}">affers list</a>
	</div>

</body>
</html>